name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.1-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx playwright test

      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          path: html/report
          name: Main report
        if: failure() || success()

      - name: Get report
        uses: actions/download-artifact@v3
        with:
          name: Main report
        if: failure() || success()